package com.idaoben.web.monitor.dao.repository;

import com.idaoben.web.common.dao.BaseRepository;
import com.idaoben.web.monitor.dao.entity.Action;

import java.util.List;

/**
*
* 应用行为 Dao接口
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
public interface ActionRepository extends BaseRepository<Action, String> {

    void deleteByTaskIdIn(List<Long> taskIds);

}