package com.idaoben.web.monitor.dao.repository;

import com.idaoben.web.monitor.dao.entity.Action;
import com.idaoben.web.common.dao.BaseRepository;

/**
*
* 应用行为 Dao接口
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
public interface ActionRepository extends BaseRepository<Action, Long> {
}