package com.idaoben.web.monitor.dao.repository;

import com.idaoben.web.common.dao.BaseRepository;
import com.idaoben.web.monitor.dao.entity.Favorite;

/**
*
* 软件 Dao接口
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
public interface FavoriteRepository extends BaseRepository<Favorite, Long> {
}