package com.idaoben.web.monitor.dao.repository;

import com.idaoben.web.common.dao.BaseRepository;
import com.idaoben.web.monitor.dao.entity.RegisterRecord;
import org.junit.Test;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.transaction.annotation.Transactional;

/**
*
* 注册记录 Dao接口
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
public interface RegisterRecordRepository extends BaseRepository<RegisterRecord, Long> {

    @Query(value = "select * from t_register_record x where x.company_name = ?1 and x.creation_time = ?2 limit 1", nativeQuery = true)
    RegisterRecord findByCompanyAndCT(String companyName, String creationTime);

    @Transactional
    @Modifying
    @Query(value = "update t_register_record set number = ?2 where id = ?1", nativeQuery = true)
    void consumeRegisterFile(Long id, Integer number);
}