package com.idaoben.web.monitor.web.dto;

import com.idaoben.utils.dto_assembler.annotation.EnableAssembling;
import com.idaoben.utils.dto_assembler.annotation.Mapping;
import com.idaoben.utils.dto_assembler.annotation.TypeMapping;
import com.idaoben.web.monitor.dao.entity.RegisterRecord;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
*
* 注册记录 Dto接口
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
@ApiModel
@EnableAssembling(mappings = @TypeMapping(from = RegisterRecord.class))
public interface RegisterRecordDto {

    @ApiModelProperty("公司名称")
    @Mapping
    String getCompanyName();

    @ApiModelProperty("总共使用次数")
    @Mapping
    Integer getCount();

    @ApiModelProperty("当前使用次数")
    @Mapping
    Integer getNumber();
}