spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/monitor
    username: monitor
    password: monitor
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
      show-sql: false
    open-in-view: false
  h2.console.enabled: true

logging:
  level:
    org.hibernate.SQL: info
    com.idaoben: debug
    com.idaoben.utils.dto_assembler.MappingClassGenerator: info
    ControllerMethodLoggingAspect: debug

daoben:
  framework:
    file: false
    url:
      file: api/admin/file
    captcha: false
    captcha-disable: true
    api-method-logging: false