spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/monitor2
    username: monitor
    password: monitor
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
      show-sql: false
    open-in-view: false
  h2.console.enabled: true

logging:
  level:
    org.hibernate.SQL: info
    com.idaoben: debug
    com.idaoben.utils.dto_assembler.MappingClassGenerator: info

monitor:
  auto-open-browser: false
  tracer-debug: false
  linux-user:
  activation-file-path: C:/Users/daoben-pc/IdeaProjects/springbootTest/target/classes/register.key
  encode-rules: daoben
  valid-time-range: 10
  software:
    map: {'qq.exe':'腾讯QQ'}