package com.idaoben.web.monitor.service.impl;

import com.idaoben.web.monitor.dao.entity.Action;
import com.idaoben.web.common.service.impl.BaseServiceImpl;
import com.idaoben.web.monitor.service.ActionService;
import org.springframework.stereotype.Service;

/**
*
* 应用行为服务实现serviceImpl
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
@Service
public class ActionServiceImpl extends BaseServiceImpl<Action, Long> implements ActionService {
}