package com.idaoben.web.monitor.service.impl;

import com.idaoben.web.common.service.impl.BaseServiceImpl;
import com.idaoben.web.monitor.dao.entity.Favorite;
import com.idaoben.web.monitor.service.FavoriteService;
import org.springframework.stereotype.Service;

/**
*
* 软件服务实现serviceImpl
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
@Service
public class FavoriteServiceImpl extends BaseServiceImpl<Favorite, Long> implements FavoriteService {
}