package com.idaoben.web.monitor.service.impl;

import com.idaoben.web.common.service.impl.BaseServiceImpl;
import com.idaoben.web.monitor.dao.entity.Software;
import com.idaoben.web.monitor.service.SoftwareService;
import org.springframework.stereotype.Service;

/**
*
* 软件服务实现serviceImpl
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
@Service
public class SoftwareServiceImpl extends BaseServiceImpl<Software, Long> implements SoftwareService {
}