package com.idaoben.web.monitor.service.impl;

import com.idaoben.web.common.service.impl.BaseServiceImpl;
import com.idaoben.web.monitor.dao.entity.Task;
import com.idaoben.web.monitor.service.TaskService;
import org.springframework.stereotype.Service;

/**
*
* 任务服务实现serviceImpl
* Generated by DAOBEN CODE GENERATOR
* @author  Daoben Code Generator
*/
@Service
public class TaskServiceImpl extends BaseServiceImpl<Task, Long> implements TaskService {
}