package com.idaoben.web.monitor.service;

import com.idaoben.web.monitor.dao.entity.Action;
import com.idaoben.web.common.service.BaseService;

import java.util.List;

/**
 *
 * 应用行为服务service
 * Generated by DAOBEN CODE GENERATOR
 * @author  Daoben Code Generator
 */
public interface ActionService extends BaseService<Action, String> {

    void deleteByTaskIds(List<Long> taskIds);

}
