package com.idaoben.web.monitor.service;

import com.idaoben.web.common.service.BaseService;
import com.idaoben.web.monitor.dao.entity.Favorite;

/**
 *
 * 软件服务service
 * Generated by DAOBEN CODE GENERATOR
 * @author  Daoben Code Generator
 */
public interface FavoriteService extends BaseService<Favorite, Long> {

}
