package com.idaoben.web.monitor.service;

import com.idaoben.web.common.service.BaseService;
import com.idaoben.web.monitor.dao.entity.RegisterRecord;

/**
 *
 * 注册记录服务service
 * Generated by DAOBEN CODE GENERATOR
 * @author  Daoben Code Generator
 */
public interface RegisterRecordService extends BaseService<RegisterRecord, Long> {
    RegisterRecord findByCompanyAndCT(String companyName, String creationTime);

    void consumeRegisterFile(Long id, Integer number);
}
