package com.idaoben.web.monitor.service;

import com.idaoben.web.common.service.BaseService;
import com.idaoben.web.monitor.dao.entity.Software;

/**
 *
 * 软件服务service
 * Generated by DAOBEN CODE GENERATOR
 * @author  Daoben Code Generator
 */
public interface SoftwareService extends BaseService<Software, Long> {

}
