package com.idaoben.web.monitor.service;

import com.idaoben.web.common.service.BaseService;
import com.idaoben.web.monitor.dao.entity.Task;

/**
 *
 * 任务服务service
 * Generated by DAOBEN CODE GENERATOR
 * @author  Daoben Code Generator
 */
public interface TaskService extends BaseService<Task, Long> {

    void deleteBySoftwareId(String softwareId);

    void deleteTaskAndAction(Long taskId);

    void deleteTaskAndActionBySoftwareId(String softwareId);
}
